# This is a sample build configuration for all languages.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
# image: docker-image:tag

pipelines:
  default:
    - step:
        script:
          - git push https://serge_van_den_oever%40hotmail.com:$AZURE_PASSWORD@amppwaapps.scm.azurewebsites.net/AmpPwaApps.git master
          - echo "Done."